server:
  port: 80

eureka:
  client:
    register-with-eureka: true # 表示是否将自己注册进EurekaServer默认true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版

ribbon:   # 设置feign客户端超时时间(openFeign默认支持ribbon)
  ReadTimeout : 5000    # 指的是建立连接所用的时间，适用于网络正常的情况下，两端连接所用的时间
  ConnectTimeOut: 5000  # 指的是建立连接后从服务器取到可用资源所用的时间
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.mingqian.springboot.service.PaymentService: debug